import React, { useEffect, useRef, useState } from 'react';
export function Integrations({ state, chatId, call, run }: { state: any; chatId: string; call: (type: string, data?: any) => Promise<any>; run: (fn: () => Promise<any>) => Promise<any> }) {
  const [skills, setSkills] = useState<any>(); const [paths, setPaths] = useState(''); const [extensions, setExtensions] = useState('');
  const [result, setResult] = useState(''); const [checking, setChecking] = useState(''); const [adding, setAdding] = useState(false);
  const [name, setName] = useState(''); const [kind, setKind] = useState('stdio'); const [endpoint, setEndpoint] = useState(''); const [args, setArgs] = useState('[]'); const [secrets, setSecrets] = useState('{}');
  const [config, setConfig] = useState(''); const servers = state.mcpServers || [], busy = state.chats.some((c: any) => c.busy);
  const [disabledSkills, setDisabledSkills] = useState<string[]>(state.disabledSkills || []); const skillSaving = useRef(false);
  useEffect(() => { if (!skillSaving.current) setDisabledSkills(state.disabledSkills || []); }, [state.disabledSkills?.join()]);
  const toggleSkill = async (path: string, enabled: boolean) => {
    const previous = disabledSkills, next = enabled ? previous.filter(p => p !== path) : [...previous, path]; setDisabledSkills(next); skillSaving.current = true;
    try { await call('configure', { disabledSkills: next }); } catch (error) { setDisabledSkills(previous); throw error; } finally { skillSaving.current = false; }
  };
  const load = async () => setSkills(await call('skills_list', { chatId }));
  useEffect(() => { setPaths((state.skillPaths || []).join('\n')); setExtensions((state.extensionPaths || []).join('\n')); load().catch(() => {}); }, [chatId, state.skillPaths?.join(), state.disabledSkills?.join()]);
  useEffect(() => setConfig(JSON.stringify({ mcpServers: Object.fromEntries(servers.map((server: any) => { const { name, ...rest } = server; return [name, rest]; })) }, null, 2)), [JSON.stringify(servers)]);
  const saveServers = (next: any) => run(() => call('configure', { mcpServers: next }));
  return <section aria-label="Skills and MCP settings"><h3>Skills</h3><p className="muted">Use installed SKILL.md instructions with any chat provider. Autoum finds Pi, Codex and .agents skills automatically.</p>
    <label>Additional skill folders<textarea aria-label="Additional skill folders" value={paths} onChange={e => setPaths(e.target.value)} rows={3} placeholder="One folder or SKILL.md path per line" /></label>
    <button disabled={busy} onClick={() => run(async () => { await call('configure', { skillPaths: paths.split('\n').map(s => s.trim()).filter(Boolean) }); await load(); })}>Save skill folders</button><button onClick={() => run(load)}>Refresh skills</button>
    <details><summary>Installed skills · {skills?.skills.length || 0}</summary>{skills?.skills.map((skill: any) => <label className="skill-option" key={skill.filePath}><input type="checkbox" aria-label={'Enable skill ' + skill.name} checked={!disabledSkills.includes(skill.filePath)} disabled={busy} onChange={e => run(() => toggleSkill(skill.filePath, e.target.checked))} /><span><strong>{skill.name}</strong><small>{skill.description}</small><small>{skill.filePath}</small></span></label>)}{skills?.diagnostics.length > 0 && <p className="muted">Some skills could not load. Check their SKILL.md name, description and paths.</p>}</details>
    <h3>MCP servers</h3><p className="muted">Connect local tools or remote services through the official MCP SDK. Calls follow the chat’s permission mode. Credentials stay in private local configuration.</p>
    {servers.map((server: any) => <div className="mcp-server" key={server.name}><label className="model-toggle"><input type="checkbox" aria-label={'Enable MCP ' + server.name} checked={server.enabled !== false} disabled={busy} onChange={e => saveServers(servers.map((s: any) => s.name === server.name ? { ...s, enabled: e.target.checked } : s))} /><strong>{server.name}</strong></label><small>{server.command || server.url}</small><div><button disabled={checking !== ''} onClick={() => run(async () => { setChecking(server.name); setResult(''); try { const r = await call('mcp_test', { name: server.name }); setResult(server.name + ' connected · ' + r.tools.length + ' tools' + (r.more ? '+' : '')); } finally { setChecking(''); } })}>{checking === server.name ? 'Connecting…' : 'Test connection'}</button><button className="danger" disabled={busy} aria-label={'Remove MCP ' + server.name} onClick={() => saveServers(servers.filter((s: any) => s.name !== server.name))}>Remove</button></div></div>)}
    {result && <p role="status">{result}</p>}<button disabled={busy} onClick={() => setAdding(v => !v)}>{adding ? 'Cancel' : 'Add MCP server'}</button>
    {adding && <form onSubmit={e => { e.preventDefault(); run(async () => { const server = kind === 'stdio' ? { name, command: endpoint, args: JSON.parse(args), env: JSON.parse(secrets) } : { name, url: endpoint, transport: kind, headers: JSON.parse(secrets) }; await call('configure', { mcpServers: [...servers, server] }); setAdding(false); setName(''); setEndpoint(''); setSecrets('{}'); }); }}><label>Name<input aria-label="MCP server name" value={name} onChange={e => setName(e.target.value)} required /></label><label>Connection<select aria-label="MCP transport" value={kind} onChange={e => setKind(e.target.value)}><option value="stdio">Local program</option><option value="http">Streamable HTTP</option><option value="sse">Legacy SSE</option></select></label><label>{kind === 'stdio' ? 'Executable' : 'Server URL'}<input aria-label="MCP endpoint" value={endpoint} onChange={e => setEndpoint(e.target.value)} required placeholder={kind === 'stdio' ? 'npx' : 'https://example.com/mcp'} /></label>{kind === 'stdio' && <label>Arguments (JSON array)<textarea aria-label="MCP arguments" value={args} onChange={e => setArgs(e.target.value)} placeholder={'["-y", "@example/mcp-server"]'} /></label>}<label>{kind === 'stdio' ? 'Environment variables' : 'Headers'} (JSON)<textarea aria-label="MCP credentials" value={secrets} onChange={e => setSecrets(e.target.value)} placeholder={'{"TOKEN":"${env:MY_TOKEN}"}'} /></label><button disabled={busy}>Save MCP server</button></form>}
    <details><summary>Import or edit MCP configuration</summary><p className="muted">Paste a standard mcpServers object. [saved] preserves an existing private value; {'${env:NAME}'} reads an environment variable.</p><textarea aria-label="MCP configuration" value={config} onChange={e => setConfig(e.target.value)} rows={9} spellCheck={false} /><button disabled={busy} onClick={() => run(() => call('configure', { mcpServers: JSON.parse(config) }))}>Save MCP configuration</button></details>
    <details><summary>Pi extensions</summary><label>Pi extension paths<textarea aria-label="Pi extension paths" value={extensions} onChange={e => setExtensions(e.target.value)} rows={3} /></label><button disabled={busy} onClick={() => run(() => call('configure', { extensionPaths: extensions.split('\n').map(s => s.trim()).filter(Boolean) }))}>Save Pi extensions</button></details>
  </section>;
}
